.\" Copyright (C) 2008–2013 Ryan Kavanagh <rak@debian.org>
.TH FRESCOBALDI 1 "May 2013" "LilyPond Music Editor"
.SH NAME
frescobaldi
\- LilyPond Music Editor
.SH SYNOPSIS
frescobaldi [options] files 
.SH DESCRIPTION
LilyPond Music Editor
.SH OPTIONS
.SS
.SS Arguments:
.TP
.B files
LilyPond files to open, may also be textedit URLs
.SS Options:
.TP
.B \-v,  \-\-version  
Show version information
.TP
.B \-h,  \-\-help
Show help about options and exit
.TP
.B \-e ENC,  \-\-encoding=ENC
Encoding to use
.TP
.B \-l NUM,  \-\-line=NUM
Line number to go to, starting at 1
.TP
.B \-c NUM,  \-\-column=NUM
Column to go to, starting at 0
.TP
.B  \-\-start  <session>
Session to start (`-' for empty session)
.TP
.B  \-\-list\-sessions
List the session names and exit
.TP
.B \-n,  \-\-new  
Always start a new instance

.SH SEE ALSO
Frescobaldi features a user manual accessible via the
.BR "User Guide"
entry in the
.BR "Help"
menu.

.SH AUTHORS
\fBfrescobaldi\fR is written and is copyrighted by:
Copyright \[co] 2008\(en2013  Wilbert Berendsen
<info\@wilbertberendsen.nl>

On Debian systems, the full list of contributors and copyright
holders may be found at
.BR "`/usr/share/doc/frescobaldi/copyright'" .

This man page was written by Ryan Kavanagh <rak\@debian.org> for the Debian
project, but may be used by others. Both this manpage and \fBfrescobaldi\fR are
released under the GNU General Public License, version 2 or (at your option) any
later version.
