#!/usr/bin/env python3

# -*- coding: utf-8 -*-
# This file is part of the Frescobaldi project, http://www.frescobaldi.org/
#
# Copyright (c) 2008 - 2020 by Wilbert Berendsen
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# See http://www.gnu.org/licenses/ for more information.

"""Frescobaldi.

This script should be placed anywhere in the path, and the Python module
frescobaldi_app contains the rest of the application.
"""

import sys

# Enable all Python warnings, unless overridden (with
# "python -W<something> frescobaldi").
if not sys.warnoptions:
    import warnings
    warnings.simplefilter("default")

from frescobaldi_app import toplevel
toplevel.install()              # Add the path to frescobaldi_app to sys.path

import checks                   # check whether Frescobaldi really can run

import main
import app

app.instantiate()               # Construct QApplication object
main.main()                     # Parse command line, create windows etc

sys.excepthook = app.excepthook # Show Python errors in a bugreport window

sys.exit(app.run())
