#! python
# -*- coding: utf-8;

# Do not edit, this file is generated. See generate.py.

from __future__ import unicode_literals


language_names = {
"C": {
 "aa":"Afar",
 "ab":"Abkhazian",
 "ae":"Avestan",
 "af":"Afrikaans",
 "am":"Amharic",
 "ar":"Arabic",
 "as":"Assamese",
 "ast":"Asturian",
 "ay":"Aymara",
 "az":"Azerbaijani",
 "ba":"Bashkir",
 "be":"Belarusian",
 "be@latin":"Belarusian (Latin)",
 "bg":"Bulgarian",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengali",
 "bn_IN":"Bengali (India)",
 "bo":"Tibetan",
 "br":"Breton",
 "bs":"Bosnian",
 "ca":"Catalan",
 "ca@valencia":"Catalan (Valencian)",
 "ce":"Chechen",
 "ch":"Chamorro",
 "co":"Corsican",
 "crh":"Crimean Tatar",
 "cs":"Czech",
 "csb":"Kashubian",
 "cu":"Church Slavic",
 "cv":"Chuvash",
 "cy":"Welsh",
 "da":"Danish",
 "de":"German",
 "dsb":"Lower Sorbian",
 "dz":"Dzongkha",
 "el":"Greek",
 "en":"English",
 "en_GB":"British English",
 "en_US":"American English",
 "eo":"Esperanto",
 "es":"Spanish",
 "et":"Estonian",
 "eu":"Basque",
 "fa":"Farsi (Persian)",
 "fi":"Finnish",
 "fj":"Fijian",
 "fo":"Faroese",
 "fr":"French",
 "fy":"Frisian",
 "ga":"Irish Gaelic",
 "gd":"Gaelic",
 "gl":"Galician",
 "gn":"Guarani",
 "gu":"Gujarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"Hebrew",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Croatian",
 "hsb":"Upper Sorbian",
 "hu":"Hungarian",
 "hy":"Armenian",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonesian",
 "ie":"Interlingue",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"Icelandic",
 "it":"Italian",
 "iu":"Inuktitut",
 "ja":"Japanese",
 "jv":"Javanese",
 "ka":"Georgian",
 "ki":"Kikuyu",
 "kk":"Kazakh",
 "kl":"Kalaallisut",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Korean",
 "ks":"Kashmiri",
 "ku":"Kurdish",
 "kv":"Komi",
 "kw":"Cornish",
 "ky":"Kirghiz",
 "la":"Latin",
 "lb":"Luxembourgish",
 "li":"Limburgan",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Lithuanian",
 "lv":"Latvian",
 "mai":"Maithili",
 "mg":"Malagasy",
 "mh":"Marshallese",
 "mi":"Maori",
 "mk":"Macedonian",
 "ml":"Malayalam",
 "mn":"Mongolian",
 "mo":"Moldavian",
 "mr":"Marathi",
 "ms":"Malay",
 "mt":"Maltese",
 "my":"Burmese",
 "na":"Nauru",
 "nb":"Norwegian Bokmål",
 "nd":"Ndebele, North",
 "nds":"Low Saxon",
 "ne":"Nepali",
 "ng":"Ndonga",
 "nl":"Dutch",
 "nn":"Norwegian Nynorsk",
 "nr":"Ndebele, South",
 "nso":"Northern Sotho",
 "nv":"Navajo",
 "ny":"Chichewa",
 "oc":"Occitan",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Ossetian",
 "pa":"Punjabi/Panjabi",
 "pi":"Pali",
 "pl":"Polish",
 "ps":"Pushto",
 "pt":"Portuguese",
 "pt_BR":"Brazilian Portuguese",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Romanian",
 "rom":"Romany",
 "ru":"Russian",
 "rw":"Kinyarwanda",
 "sa":"Sanskrit",
 "sc":"Sardinian",
 "sd":"Sindhi",
 "se":"Northern Sami",
 "sg":"Sango",
 "si":"Sinhala",
 "sk":"Slovak",
 "sl":"Slovenian",
 "sm":"Samoan",
 "sn":"Shona",
 "so":"Somali",
 "sq":"Albanian",
 "sr":"Serbian",
 "sr@ijekavian":"Serbian Ijekavian",
 "sr@ijekavianlatin":"Serbian Ijekavian Latin",
 "sr@latin":"Serbian Latin",
 "ss":"Swati",
 "st":"Sotho, Southern",
 "su":"Sundanese",
 "sv":"Swedish",
 "sw":"Swahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Tajik",
 "th":"Thai",
 "ti":"Tigrinya",
 "tk":"Turkmen",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turkish",
 "ts":"Tsonga",
 "tt":"Tatar",
 "tw":"Twi",
 "ty":"Tahitian",
 "ug":"Uighur",
 "uk":"Ukrainian",
 "ur":"Urdu",
 "uz":"Uzbek",
 "uz@cyrillic":"Uzbek (Cyrillic)",
 "ven":"Venda",
 "vi":"Vietnamese",
 "vo":"Volapük",
 "wa":"Walloon",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Yiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Chinese",
 "zh_CN":"Chinese Simplified",
 "zh_HK":"Chinese (Hong Kong)",
 "zh_TW":"Chinese Traditional",
 "zu":"Zulu",
},
"cs": {
 "aa":"Afar",
 "ab":"Abcházský",
 "ae":"Avestánský",
 "af":"Afrikánský",
 "am":"Amharský",
 "ar":"Arabský",
 "as":"Asamský",
 "ast":"Asturijský",
 "ay":"Aymara",
 "az":"Ázerbajdžánský",
 "ba":"Baškirský",
 "be":"Běloruský",
 "be@latin":"Běloruský (latinka)",
 "bg":"Bulharský",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengálský",
 "bn_IN":"Bengálský (Indie)",
 "bo":"Tibetský",
 "br":"Bretonský",
 "bs":"Bosenský",
 "ca":"Katalánský",
 "ca@valencia":"Katalánský (Valencie)",
 "ce":"Čečenský",
 "ch":"Chamorro",
 "co":"Korsický",
 "crh":"Krymská tatarština",
 "cs":"Český",
 "csb":"Kašubský",
 "cu":"Staroslověnský",
 "cv":"Čuvašský",
 "cy":"Welšský",
 "da":"Dánský",
 "de":"Německý",
 "dsb":"Dolnolužicko srbský",
 "dz":"Dzongkha",
 "el":"Řecký",
 "en":"Anglický",
 "en_GB":"Britská angličtina",
 "en_US":"Americká angličtina",
 "eo":"Esperanto",
 "es":"Španělský",
 "et":"Estonský",
 "eu":"Baskický",
 "fa":"Farsi (Perský)",
 "fi":"Finský",
 "fj":"Fidžijský",
 "fo":"Faerský",
 "fr":"Francouzský",
 "fy":"Fríský",
 "ga":"Galský (irština)",
 "gd":"Galský",
 "gl":"Haličský",
 "gn":"Guarani",
 "gu":"Gujarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"Hebrejský",
 "hi":"Hindský",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Chorvatský",
 "hsb":"Hornolužicko srbský",
 "hu":"Maďarský",
 "hy":"Arménský",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonéský",
 "ie":"Interlingue",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"Islandský",
 "it":"Italský",
 "iu":"Inuktitut",
 "ja":"Japonský",
 "jv":"Jávský",
 "ka":"Gruzínský",
 "ki":"Kikuyu",
 "kk":"Kazašský",
 "kl":"Kalaallisut",
 "km":"Kmérský",
 "kn":"Kannada",
 "ko":"Korejský",
 "ks":"Kašmírský",
 "ku":"Kurdský",
 "kv":"Komi",
 "kw":"Kornišský",
 "ky":"Kyrgizský",
 "la":"Latina",
 "lb":"Lucemburský",
 "li":"Limburgan",
 "ln":"Lingala",
 "lo":"Laoský",
 "lt":"Litevský",
 "lv":"Lotyšský",
 "mai":"Maithili",
 "mg":"Malagasy",
 "mh":"Marshallský",
 "mi":"Maorský",
 "mk":"Makedonský",
 "ml":"Malayalam",
 "mn":"Mongolský",
 "mo":"Moldavský",
 "mr":"Marathi",
 "ms":"Malajský",
 "mt":"Maltézský",
 "my":"Burmský",
 "na":"Nauru",
 "nb":"Norský (Bokmål)",
 "nd":"Ndebele, Severní",
 "nds":"Dolnosaský",
 "ne":"Nepálský",
 "ng":"Ndonga",
 "nl":"Holandský",
 "nn":"Norský (Nynorsk)",
 "nr":"Ndebele, Jižní",
 "nso":"Severní Sotho",
 "nv":"Navajo",
 "ny":"Chichewa",
 "oc":"Okcitánský",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Osetský",
 "pa":"Pandžábský",
 "pi":"Pali",
 "pl":"Polský",
 "ps":"Pushto",
 "pt":"Portugalský",
 "pt_BR":"Portugalský (Brazílie)",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Rumunský",
 "rom":"Romský",
 "ru":"Ruský",
 "rw":"Kinyarwanda",
 "sa":"Sanskrit",
 "sc":"Sardinský",
 "sd":"Sindhi",
 "se":"Severní Sami",
 "sg":"Sango",
 "si":"Sinhalský",
 "sk":"Slovenský",
 "sl":"Slovinský",
 "sm":"Samojský",
 "sn":"Shona",
 "so":"Somálský",
 "sq":"Albánský",
 "sr":"Srbský",
 "sr@latin":"Srbský (latinka)",
 "ss":"Swati",
 "st":"Sotho, Jižní",
 "su":"Sundanský",
 "sv":"Švédský",
 "sw":"Svahilský",
 "ta":"Tamilský",
 "te":"Telugu",
 "tg":"Tádžikský",
 "th":"Thajský",
 "ti":"Tigrinya",
 "tk":"Turkmenský",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turecký",
 "ts":"Tsonga",
 "tt":"Tatarský",
 "tw":"Twi",
 "ty":"Tahitský",
 "ug":"Uighur",
 "uk":"Ukrajinský",
 "ur":"Urdu",
 "uz":"Uzbecký",
 "uz@cyrillic":"Uzbecký (azbuka)",
 "ven":"Venda",
 "vi":"Vietnamský",
 "vo":"Volapük",
 "wa":"Wallonský",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Jidiš",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Čínský",
 "zh_CN":"Čínský (zjednodušená)",
 "zh_HK":"Čínský (Hong Kong)",
 "zh_TW":"Čínský (tradiční)",
 "zu":"Zulu",
},
"de": {
 "aa":"Afar",
 "ab":"Abhasisch",
 "ae":"Avestisch",
 "af":"Afrikaans",
 "am":"Amharisch",
 "ar":"Arabisch",
 "as":"Assamesisch",
 "ast":"Asturisch",
 "ay":"Aimara",
 "az":"Aserbaidschanisch",
 "ba":"Baschkirisch",
 "be":"Weißrussisch",
 "be@latin":"Weißrussisch (lat. Alphabet)",
 "bg":"Bulgarisch",
 "bh":"Biharisch",
 "bi":"Bislama",
 "bn":"Bengalisch",
 "bn_IN":"Bengalisch (Indien)",
 "bo":"Tibetisch",
 "br":"Bretonisch",
 "bs":"Bosnisch",
 "ca":"Katalanisch",
 "ca@valencia":"Katalanisch (Valenciana)",
 "ce":"Tschetschenisch",
 "ch":"Chamorro",
 "co":"Korsisch",
 "crh":"Krimtatarisch",
 "cs":"Tschechisch",
 "csb":"Kaschubisch",
 "cu":"Kirchenslawisch",
 "cv":"Tschuwaschisch",
 "cy":"Walisisch",
 "da":"Dänisch",
 "de":"Deutsch",
 "dsb":"Niedersorbisch",
 "dz":"Dzongkha",
 "el":"Griechisch",
 "en":"Englisch",
 "en_GB":"Englisch (UK)",
 "en_US":"Englisch (US)",
 "eo":"Esperanto",
 "es":"Spanisch",
 "et":"Estnisch",
 "eu":"Baskisch",
 "fa":"Farsi (Persisch)",
 "fi":"Finnisch",
 "fj":"Fidschi",
 "fo":"Färöisch",
 "fr":"Französisch",
 "fy":"Friesisch",
 "ga":"Irisches Gälisch",
 "gd":"Gälisch",
 "gl":"Galicisch",
 "gn":"Guarani",
 "gu":"Gujarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"Hebräisch",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Kroatisch",
 "hsb":"Obersorbisch",
 "hu":"Ungarisch",
 "hy":"Armenisch",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonesisch",
 "ie":"Interlingue",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"Isländisch",
 "it":"Italienisch",
 "iu":"Inuktitut",
 "ja":"Japanisch",
 "jv":"Javanisch",
 "ka":"Georgisch",
 "ki":"Kikuyu",
 "kk":"Kasachisch",
 "kl":"Kalaallisut",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Koreanisch",
 "ks":"Kashmiri",
 "ku":"Kurdisch",
 "kv":"Komi",
 "kw":"Kornisch",
 "ky":"Kirgisisch",
 "la":"Latein",
 "lb":"Luxemburgisch",
 "li":"Limburgisch",
 "ln":"Lingala",
 "lo":"Laotisch",
 "lt":"Litauisch",
 "lv":"Lettisch",
 "mai":"Maithili",
 "mg":"Madagassisch",
 "mh":"Marshallisch",
 "mi":"Maori",
 "mk":"Mazedonisch",
 "ml":"Malayalam",
 "mn":"Mongolisch",
 "mo":"Moldawisch",
 "mr":"Marathi",
 "ms":"Malaiisch",
 "mt":"Maltesisch",
 "my":"Burmesisch",
 "na":"Nauruisch",
 "nb":"Norwegisch (Bokmål)",
 "nd":"Ndebele (nördliches)",
 "nds":"Niederdeutsch",
 "ne":"Nepali",
 "ng":"Oshivambo",
 "nl":"Niederländisch",
 "nn":"Norwegisch (Nynorsk)",
 "nr":"Ndebele (südliches)",
 "nso":"Nord-Sotho",
 "nv":"Navajo",
 "ny":"Nyanja",
 "oc":"Okzitanisch",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Ossetisch",
 "pa":"Pandschabi",
 "pi":"Pali",
 "pl":"Polnisch",
 "ps":"Paschtu",
 "pt":"Portugiesisch",
 "pt_BR":"Brasilianisches Portugiesisch",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Rumänisch",
 "rom":"Romani",
 "ru":"Russisch",
 "rw":"Kinyarwanda",
 "sa":"Sanskrit",
 "sc":"Sardisch",
 "sd":"Sindhi",
 "se":"Nördliches Sami",
 "sg":"Sango",
 "si":"Singhalesisch",
 "sk":"Slowakisch",
 "sl":"Slowenisch",
 "sm":"Samoanisch",
 "sn":"Shona",
 "so":"Somali",
 "sq":"Albanisch",
 "sr":"Serbisch",
 "sr@ijekavian":"Štokavisch",
 "sr@ijekavianlatin":"Štokavisch (lat. Alphabet)",
 "sr@latin":"Serbisch (lat. Alphabet)",
 "ss":"Swati",
 "st":"Südliches Sotho",
 "su":"Sundanesisch",
 "sv":"Schwedisch",
 "sw":"Swahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Tadschikisch",
 "th":"Thailändisch",
 "ti":"Tigrinja",
 "tk":"Turkmenisch",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Türkisch",
 "ts":"Tsonga",
 "tt":"Tatarisch",
 "tw":"Twi",
 "ty":"Tahitianisch",
 "ug":"Uigurisch",
 "uk":"Ukrainisch",
 "ur":"Urdu",
 "uz":"Usbekisch",
 "uz@cyrillic":"Usbekisch (Kyrillisch)",
 "ven":"Tshivenda",
 "vi":"Vietnamesisch",
 "vo":"Volapük",
 "wa":"Wallonisch",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Jiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Chinesisch",
 "zh_CN":"Chinesisch (Kurzzeichen)",
 "zh_HK":"Chinesisch (Hongkong)",
 "zh_TW":"Chinesisch (Langzeichen)",
 "zu":"Zulu",
},
"es": {
 "aa":"Afar",
 "ab":"Abjaso",
 "ae":"Avéstico",
 "af":"Afrikaans",
 "am":"Amárico",
 "ar":"Árabe",
 "as":"Asamés",
 "ast":"Asturiano",
 "ay":"Aymara",
 "az":"Azerbayano",
 "ba":"Baskir",
 "be":"Bielorruso",
 "be@latin":"Bielorruso (Latino)",
 "bg":"Búlgaro",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengalí",
 "bn_IN":"Bengalí (India)",
 "bo":"Tibetano",
 "br":"Bretón",
 "bs":"Bosnio",
 "ca":"Catalán",
 "ca@valencia":"Catalán (Valenciano)",
 "ce":"Checheno",
 "ch":"Chamorro",
 "co":"Corso",
 "crh":"Tártaro de Crimea",
 "cs":"Checo",
 "csb":"Casubio",
 "cu":"Eslavo eclesiástico",
 "cv":"Chuvasio",
 "cy":"Galés",
 "da":"Danés",
 "de":"Alemán",
 "dsb":"Bajo sorabo",
 "dz":"Dzongkha",
 "el":"Griego",
 "en":"Inglés",
 "en_GB":"Inglés británico",
 "en_US":"Inglés americano",
 "eo":"Esperanto",
 "es":"Español",
 "et":"Estonio",
 "eu":"Euskera",
 "fa":"Persa",
 "fi":"Finés",
 "fj":"Fiyiano",
 "fo":"Feroés",
 "fr":"Francés",
 "fy":"Frisio",
 "ga":"Gaélico irlandés",
 "gd":"Gaélico",
 "gl":"Gallego",
 "gn":"Guaraní",
 "gu":"Gujarati",
 "gv":"Manés",
 "ha":"Hausa",
 "he":"Hebreo",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Croata",
 "hsb":"Alto sorabo",
 "hu":"Húngaro",
 "hy":"Armenio",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonesio",
 "ie":"Idioma occidental",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"Islandés",
 "it":"Italiano",
 "iu":"Inuktitut",
 "ja":"Japonés",
 "jv":"Javanés",
 "ka":"Georgiano",
 "ki":"Kikuyu",
 "kk":"Kazajo",
 "kl":"Kalaallisut",
 "km":"Camboyano",
 "kn":"Kannada",
 "ko":"Coreano",
 "ks":"Kashmiri",
 "ku":"Kurdo",
 "kv":"Komi",
 "kw":"Cornuallés",
 "ky":"Kirguiz",
 "la":"Latín",
 "lb":"Luxemburgués",
 "li":"Limburgano",
 "ln":"Lingala",
 "lo":"Laosiano",
 "lt":"Lituano",
 "lv":"Letón",
 "mai":"Maithili",
 "mg":"Malagasio",
 "mh":"Marshalés",
 "mi":"Maorí",
 "mk":"Macedonio",
 "ml":"Malabar",
 "mn":"Mongol",
 "mo":"Moldavo",
 "mr":"Maratí",
 "ms":"Malayo",
 "mt":"Maltés",
 "my":"Burmés",
 "na":"Nauru",
 "nb":"Noruego Bokmål",
 "nd":"Ndebele del norte",
 "nds":"Bajo sajón",
 "ne":"Nepalí",
 "ng":"Ndonga",
 "nl":"Holandés",
 "nn":"Noruego Nynorsk",
 "nr":"Ndebele del sur",
 "nso":"Sotho del norte",
 "nv":"Navajo",
 "ny":"Chichewa",
 "oc":"Occitano",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Osetio",
 "pa":"Punjabi",
 "pi":"Palí",
 "pl":"Polaco",
 "ps":"Pastún",
 "pt":"Portugués",
 "pt_BR":"Portugués brasileño",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Rumano",
 "rom":"Rumaní",
 "ru":"Ruso",
 "rw":"Kinyarwanda",
 "sa":"Sánscrito",
 "sc":"Sardo",
 "sd":"Sindhi",
 "se":"Samí del norte",
 "sg":"Sango",
 "si":"Cingalés",
 "sk":"Eslovaco",
 "sl":"Esloveno",
 "sm":"Samoano",
 "sn":"Shona",
 "so":"Somalí",
 "sq":"Albanés",
 "sr":"Serbio",
 "sr@ijekavian":"Serbio ijekaviano",
 "sr@ijekavianlatin":"Serbio latino ijekaviano",
 "sr@latin":"Serbio latino",
 "ss":"Swati",
 "st":"Sotho del sur",
 "su":"Sudanés",
 "sv":"Sueco",
 "sw":"Suahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Tayiko",
 "th":"Tailandés",
 "ti":"Tigrinya",
 "tk":"Turkmenio",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turco",
 "ts":"Tsonga",
 "tt":"Tatar",
 "tw":"Twi",
 "ty":"Tahitiano",
 "ug":"Uighur",
 "uk":"Ucraniano",
 "ur":"Urdu",
 "uz":"Uzbeko",
 "uz@cyrillic":"Uzbeko (Cirílico)",
 "ven":"Venda",
 "vi":"Vietnamita",
 "vo":"Volapük",
 "wa":"Walloon",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Yiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Chino",
 "zh_CN":"Chino simplificado",
 "zh_HK":"Chino (Hong Kong)",
 "zh_TW":"Chino tradicional",
 "zu":"Zulú",
},
"fr": {
 "aa":"Afar",
 "ab":"Abkhaze",
 "ae":"Avestan",
 "af":"Afrikaans",
 "am":"Amharique",
 "ar":"Arabe",
 "as":"Assamais",
 "ast":"Asturien",
 "ay":"Aymara",
 "az":"Azerbaïdjanais",
 "ba":"Bachkir",
 "be":"Biélorusse",
 "be@latin":"Biélorusse (Latin)",
 "bg":"Bulgare",
 "bh":"Bihari",
 "bi":"Bichlamar",
 "bn":"Bengalî",
 "bn_IN":"Bengali (Inde)",
 "bo":"Tibétain",
 "br":"Breton",
 "bs":"Bosniaque",
 "ca":"Catalan",
 "ca@valencia":"Catalan (Valence)",
 "ce":"Tchétchène",
 "ch":"Chamorro",
 "co":"Corse",
 "crh":"Tatars de Crimée",
 "cs":"Tchèque",
 "csb":"Kachoube",
 "cu":"Slavon d'égise",
 "cv":"Tchouvache",
 "cy":"Gallois",
 "da":"Danois",
 "de":"Allemand",
 "dsb":"Bas-Sorabe",
 "dz":"Dzongkha",
 "el":"Grec",
 "en":"Anglais",
 "en_GB":"Anglais britannique",
 "en_US":"Anglais américain",
 "eo":"Espéranto",
 "es":"Espagnol",
 "et":"Estonien",
 "eu":"Basque",
 "fa":"Persan",
 "fi":"Finnois",
 "fj":"Fidjien",
 "fo":"Féroïen",
 "fr":"Français",
 "fy":"Frison",
 "ga":"Gaélique irlandais",
 "gd":"Gaélique",
 "gl":"Gaélicien",
 "gn":"Guarani",
 "gu":"Gujarati",
 "gv":"Mannois",
 "ha":"Haoussa",
 "he":"Hébreu",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri motu",
 "hr":"Croate",
 "hsb":"Haut-Sorabe",
 "hu":"Hongrois",
 "hy":"Arménien",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonésien",
 "ie":"Interlingue",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"Islandais",
 "it":"Italien",
 "iu":"Inuktitut",
 "ja":"Japonais",
 "jv":"Javanais",
 "ka":"Géorgien",
 "ki":"Kikuyu",
 "kk":"Kazakh",
 "kl":"Kalaallisut",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Coréen",
 "ks":"Kashmiri",
 "ku":"Kurde",
 "kv":"Komi",
 "kw":"Cornique",
 "ky":"Kirghize",
 "la":"Latin",
 "lb":"Luxembourgeois",
 "li":"Limbourgeois",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Lituanien",
 "lv":"Letton",
 "mai":"Maïthili",
 "mg":"Malgache",
 "mh":"Marshall",
 "mi":"Maori",
 "mk":"Macédonien",
 "ml":"Malayalam",
 "mn":"Mongol",
 "mo":"Moldave",
 "mr":"Marathe",
 "ms":"Malais",
 "mt":"Maltais",
 "my":"Birman",
 "na":"Nauruan",
 "nb":"Norvégien Bokmaal",
 "nd":"Ndébélé du Nord",
 "nds":"Bas saxon",
 "ne":"Népalais",
 "ng":"Ndonga",
 "nl":"Hollandais",
 "nn":"Norvégien Nynorsk",
 "nr":"Ndébélé du Sud",
 "nso":"Sotho du Nord",
 "nv":"Navaho",
 "ny":"Chichewa",
 "oc":"Occitan",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Ossète",
 "pa":"Panjabi / Punjabi",
 "pi":"Pali",
 "pl":"Polonais",
 "ps":"Pushto",
 "pt":"Portugais",
 "pt_BR":"Portugais Brésilien",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Roumain",
 "rom":"Rromani",
 "ru":"Russe",
 "rw":"Kinyarwanda",
 "sa":"Sanskrit",
 "sc":"Sarde",
 "sd":"Sindhi",
 "se":"Sami du Nord",
 "sg":"Sango",
 "si":"Cingalais",
 "sk":"Slovaque",
 "sl":"Slovène",
 "sm":"Samoan",
 "sn":"Shona",
 "so":"Somali",
 "sq":"Albanais",
 "sr":"Serbe",
 "sr@ijekavian":"Serbe Ijékavien",
 "sr@ijekavianlatin":"Serbe Ijékavien Latin",
 "sr@latin":"Serbe Latin",
 "ss":"Swati",
 "st":"Sotho du Sud",
 "su":"Soudanais",
 "sv":"Suédois",
 "sw":"Swahili",
 "ta":"Tamoul",
 "te":"Télougou",
 "tg":"Tadjik",
 "th":"Thaïlandais",
 "ti":"Tigrigna",
 "tk":"Turkmène",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turc",
 "ts":"Tsonga",
 "tt":"Tatar",
 "tw":"Twi",
 "ty":"Tahitien",
 "ug":"Uighur",
 "uk":"Ukrainien",
 "ur":"Urdu",
 "uz":"Ouzbek",
 "uz@cyrillic":"Ouzbek (Cyrillique)",
 "ven":"Venda",
 "vi":"Vietnamien",
 "vo":"Volapük",
 "wa":"Wallon",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Yiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Chinois",
 "zh_CN":"Chinois simplifié",
 "zh_HK":"Chinois (Hong Kong)",
 "zh_TW":"Chinois traditionnel",
 "zu":"Zoulou",
},
"gl": {
 "aa":"Afar",
 "ab":"Abxasio",
 "ae":"Avestaní",
 "af":"Africáner",
 "am":"Amharic",
 "ar":"Árabe",
 "as":"Asamixa",
 "ast":"Asturiano",
 "ay":"Aimará",
 "az":"Azerí",
 "ba":"Bashquir",
 "be":"Bielorruso",
 "be@latin":"Bielorruso (Latino)",
 "bg":"Búlgaro",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengalí",
 "bn_IN":"Bengalí (India)",
 "bo":"Tibetano",
 "br":"Bretón",
 "bs":"Bosnio",
 "ca":"Catalán",
 "ca@valencia":"Catalán (Valenciano)",
 "ce":"Checheno",
 "ch":"Chamorro",
 "co":"Corso",
 "crh":"Tártaro da Crimea",
 "cs":"Checo",
 "csb":"Kashubí",
 "cu":"Eslavo eclesiástico",
 "cv":"Chuvash",
 "cy":"Galés",
 "da":"Dinamarqués",
 "de":"Alemán",
 "dsb":"Baixo sórabo",
 "dz":"Dzongca",
 "el":"Grego",
 "en":"Inglés",
 "en_GB":"Inglés de GB",
 "en_US":"Inglés americano",
 "eo":"Esperanto",
 "es":"Castelán",
 "et":"Estoniano",
 "eu":"Vasco",
 "fa":"Frisón (Parsi)",
 "fi":"Finlandés",
 "fj":"Fixiano",
 "fo":"Feroés",
 "fr":"Francés",
 "fy":"Frisio",
 "ga":"Gaélico de Irlanda",
 "gd":"Gaélico",
 "gl":"Galego",
 "gn":"Guaraní",
 "gu":"Guxarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"Hebraico",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Croata",
 "hsb":"Alto sórabo",
 "hu":"Húngaro",
 "hy":"Armenio",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonesio",
 "ie":"Interlingua",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"Islandés",
 "it":"Italiano",
 "iu":"Inuktitut",
 "ja":"Xaponés",
 "jv":"Xavanés",
 "ka":"Xeorxiano",
 "ki":"Kikuyu",
 "kk":"Cazaxo",
 "kl":"Groenlandés",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Coreano",
 "ks":"Caxemir",
 "ku":"Kurdo",
 "kv":"Komi",
 "kw":"Córnico",
 "ky":"Quirguiz",
 "la":"Latín",
 "lb":"Luxemburgués",
 "li":"Limburgano",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Lituano",
 "lv":"Letón",
 "mai":"Maithili",
 "mg":"Malgaxe",
 "mh":"Marshalés",
 "mi":"Maorí",
 "mk":"Macedonio",
 "ml":"Malaialam",
 "mn":"Mongol",
 "mo":"Moldavo",
 "mr":"Marata",
 "ms":"Malaio",
 "mt":"Maltés",
 "my":"Burmés",
 "na":"Nauru",
 "nb":"Noruegués (Bokmaal)",
 "nd":"Ndebele do norte",
 "nds":"Baixo saxón",
 "ne":"Nepalí",
 "ng":"Ndonga",
 "nl":"Holandés",
 "nn":"Noruegués (Nynorsk)",
 "nr":"Ndebele do sur",
 "nso":"Sotho do norte",
 "nv":"Navaxo",
 "ny":"Chichewa",
 "oc":"Occitano",
 "om":"Oromo",
 "or":"Orisa",
 "os":"Oseto",
 "pa":"Punxabí/Panxabí",
 "pi":"Pali",
 "pl":"Polaco",
 "ps":"Pushto",
 "pt":"Portugués",
 "pt_BR":"Portugués do Brasil",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Romanés",
 "rom":"Romaní",
 "ru":"Ruso",
 "rw":"Quiñaruanda",
 "sa":"Sánscrito",
 "sc":"Sardo",
 "sd":"Sindhi",
 "se":"Sami do norte",
 "sg":"Sango",
 "si":"Sinhala",
 "sk":"Eslovaco",
 "sl":"Esloveno",
 "sm":"Samoano",
 "sn":"Shona",
 "so":"Somalí",
 "sq":"Albanés",
 "sr":"Serbio",
 "sr@ijekavian":"Serbio ixtocavio",
 "sr@ijekavianlatin":"Serbio ishtocavio Latino",
 "sr@latin":"Serbio latino",
 "ss":"Swati",
 "st":"Sotho do sur",
 "su":"Sudanés",
 "sv":"Sueco",
 "sw":"Swahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Taxico",
 "th":"Tailandés",
 "ti":"Tigrignan",
 "tk":"Turquemeno",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turco",
 "ts":"Tsonga",
 "tt":"Tártaro",
 "tw":"Twi",
 "ty":"Tahitiano",
 "ug":"Uighur",
 "uk":"Ucraíno",
 "ur":"Urdú",
 "uz":"Usbeco",
 "uz@cyrillic":"Usbeco (Cirílico)",
 "ven":"Venda",
 "vi":"Vietnamita",
 "vo":"Volapük",
 "wa":"Valón",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Iídiche",
 "yo":"Yorubá",
 "za":"Chuan",
 "zh":"Chinés",
 "zh_CN":"Chinés simplificado",
 "zh_HK":"Chinés (Hong Kong)",
 "zh_TW":"Chinés Tradicional",
 "zu":"Zulú",
},
"hu": {
 "aa":"Afar",
 "ab":"Abház",
 "ae":"Avesztáni",
 "af":"Afrikaans",
 "am":"Amhár",
 "ar":"Arab",
 "as":"Asszámi",
 "ast":"Asztúriai",
 "ay":"Ajmara",
 "az":"Azerbajdzsán",
 "ba":"Baskír",
 "be":"Belorusz",
 "be@latin":"Belorusz (latin betűs)",
 "bg":"Bolgár",
 "bh":"Bihari",
 "bi":"Biszlama",
 "bn":"Bengáli",
 "bn_IN":"Bengáli (India)",
 "bo":"Tibeti",
 "br":"Breton",
 "bs":"Bosnyák",
 "ca":"Katalán",
 "ce":"Csecsen",
 "ch":"Chamorro",
 "co":"Korzikai",
 "crh":"Krími tatár",
 "cs":"Cseh",
 "csb":"Kasub",
 "cu":"Szláv (egyházi)",
 "cv":"Csuvas",
 "cy":"Velszi",
 "da":"Dán",
 "de":"Német",
 "dsb":"Alsó szorb",
 "dz":"Dzongkha",
 "el":"Görög",
 "en":"Angol",
 "en_GB":"Angol (brit)",
 "en_US":"Angol (amerikai)",
 "eo":"Eszperantó",
 "es":"Spanyol",
 "et":"Észt",
 "eu":"Baszk",
 "fa":"Fárszi (perzsa)",
 "fi":"Finn",
 "fj":"Fidzsi",
 "fo":"Faröei",
 "fr":"Francia",
 "fy":"Fríz",
 "ga":"Gall (ír)",
 "gd":"Gall",
 "gl":"Galíciai",
 "gn":"Guarani",
 "gu":"Gudzsarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"Héber",
 "hi":"Hindi",
 "hne":"Cshattíszgarhi",
 "ho":"Hiri motu",
 "hr":"Horvát",
 "hsb":"Felső szorb",
 "hu":"Magyar",
 "hy":"Örmény",
 "hz":"Hereró",
 "ia":"Interlingua",
 "id":"Indonéz",
 "ie":"Interlingue",
 "ik":"Inupiak",
 "io":"Ido",
 "is":"Izlandi",
 "it":"Olasz",
 "iu":"Inuktitut",
 "ja":"Japán",
 "jv":"Jávai",
 "ka":"Grúz",
 "ki":"Kikuju",
 "kk":"Kazah",
 "kl":"Kalaalliszut",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Koreai",
 "ks":"Kasmír",
 "ku":"Kurd",
 "kv":"Komi",
 "kw":"Korn",
 "ky":"Kirgiz",
 "la":"Latin",
 "lb":"Luxemburgi",
 "li":"Limburgi",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Litván",
 "lv":"Lett",
 "mai":"Maithili",
 "mg":"Malagazi",
 "mh":"Marsalli",
 "mi":"Maori",
 "mk":"Macedón",
 "ml":"Malajalam",
 "mn":"Mongol",
 "mo":"Moldáv",
 "mr":"Marati",
 "ms":"Maláj",
 "mt":"Máltai",
 "my":"Burmai",
 "na":"Nauru",
 "nb":"Norvég (bokmal)",
 "nd":"Ndebele (északi)",
 "nds":"Alsószász",
 "ne":"Nepáli",
 "ng":"Ndonga",
 "nl":"Holland",
 "nn":"Norvég (nynorsk)",
 "nr":"Ndebele (déli)",
 "nso":"Északi sotho",
 "nv":"Navajo",
 "ny":"Csicseva",
 "oc":"Okcitán",
 "om":"Oromo",
 "or":"Orija",
 "os":"Oszét",
 "pa":"Pandzsabi",
 "pi":"Pali",
 "pl":"Lengyel",
 "ps":"Pusto",
 "pt":"Portugál",
 "pt_BR":"Portugál (brazil)",
 "qu":"Kecsua",
 "rn":"Rundi",
 "ro":"Román",
 "rom":"Lovári cigány",
 "ru":"Orosz",
 "rw":"Kinjarvanda",
 "sa":"Szanszkrit",
 "sc":"Szardíniai",
 "sd":"Szindi",
 "se":"Északi szami",
 "sg":"Szangó",
 "si":"Szingaléz",
 "sk":"Szlovák",
 "sl":"Szlovén",
 "sm":"Szamoai",
 "sn":"Sona",
 "so":"Szomáli",
 "sq":"Albán",
 "sr":"Szerb",
 "sr@ijekavian":"Szerb (ijekavica)",
 "sr@ijekavianlatin":"Szerb (ijekavica, latin betűs)",
 "sr@latin":"Szerb (latin betűs)",
 "ss":"Szvati",
 "st":"Sotho (déli)",
 "su":"Szundanéz",
 "sv":"Svéd",
 "sw":"Szvahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Tádzsik",
 "th":"Thai",
 "ti":"Tigrinja",
 "tk":"Türkmén",
 "tn":"Tszvana",
 "to":"Tonga",
 "tr":"Török",
 "ts":"Tsonga",
 "tt":"Tatár",
 "tw":"Tvi",
 "ty":"Tahiti",
 "ug":"Ujgur",
 "uk":"Ukrán",
 "ur":"Urdu",
 "uz":"Üzbég",
 "uz@cyrillic":"Üzbég (cirill)",
 "ven":"Venda",
 "vi":"Vietnami",
 "vo":"Volapük",
 "wa":"Vallon",
 "wo":"Volof",
 "xh":"Xhosza",
 "yi":"Jiddis",
 "yo":"Joruba",
 "za":"Zhuang",
 "zh":"Kínai",
 "zh_CN":"Kínai (egyszerűsített)",
 "zh_HK":"Kínai (hongkongi)",
 "zh_TW":"Kínai (hagyományos)",
 "zu":"Zulu",
},
"it": {
 "aa":"Afar",
 "ab":"Abcaso",
 "ae":"Avestano",
 "af":"Afrikaans",
 "am":"Amarico",
 "ar":"Arabo",
 "as":"Assamese",
 "ast":"Asturiano",
 "ay":"Aymara",
 "az":"Azero",
 "ba":"Baškiro",
 "be":"Bielorusso",
 "be@latin":"Bielorusso (Latino)",
 "bg":"Bulgaro",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengalese",
 "bn_IN":"Bengalese (India)",
 "bo":"Tibetano",
 "br":"Bretone",
 "bs":"Bosniaco",
 "ca":"Catalano",
 "ca@valencia":"Catalano (Valenziano)",
 "ce":"Ceceno",
 "ch":"Chamorro",
 "co":"Corso",
 "crh":"Tataro di Crimea",
 "cs":"Ceco",
 "csb":"Casciubico",
 "cu":"Slavo ecclesiastico",
 "cv":"Ciuvascio",
 "cy":"Gallese",
 "da":"Danese",
 "de":"Tedesco",
 "dsb":"Basso sorabo",
 "dz":"Dzongkha",
 "el":"Greco",
 "en":"Inglese",
 "en_GB":"Inglese britannico",
 "en_US":"Inglese americano",
 "eo":"Esperanto",
 "es":"Spagnolo",
 "et":"Estone",
 "eu":"Basco",
 "fa":"Farsi (Persiano)",
 "fi":"Finlandese",
 "fj":"Figiano",
 "fo":"Faroese",
 "fr":"Francese",
 "fy":"Frisone",
 "ga":"Gaelico irlandese",
 "gd":"Gaelico",
 "gl":"Gallego",
 "gn":"Guaraní",
 "gu":"Gujarati",
 "gv":"Mannese",
 "ha":"Hausa",
 "he":"Ebraico",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri motu",
 "hr":"Croato",
 "hsb":"Alto sorabo",
 "hu":"Ungherese",
 "hy":"Armeno",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonesiano",
 "ie":"Interlingue",
 "ik":"Inupiak",
 "io":"Ido",
 "is":"Islandese",
 "it":"Italiano",
 "iu":"Inuktitut",
 "ja":"Giapponese",
 "jv":"Giavanese",
 "ka":"Georgiano",
 "ki":"Kikuyu",
 "kk":"Kazako",
 "kl":"Groenlandese",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Coreano",
 "ks":"Kašmiro",
 "ku":"Curdo",
 "kv":"Komi",
 "kw":"Cornico",
 "ky":"Kirghiso",
 "la":"Latino",
 "lb":"Lussemburghese",
 "li":"Limburghese",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Lituano",
 "lv":"Lettone",
 "mai":"Maithili",
 "mg":"Malgascio",
 "mh":"Marsciallese",
 "mi":"Maori",
 "mk":"Macedone",
 "ml":"Malayalam",
 "mn":"Mongolo",
 "mo":"Moldavo",
 "mr":"Marathi",
 "ms":"Malese",
 "mt":"Maltese",
 "my":"Birmano",
 "na":"Nauruano",
 "nb":"Norvegese bokmål",
 "nd":"Ndebele settentrionale",
 "nds":"Basso sassone",
 "ne":"Nepalese",
 "ng":"Ndonga",
 "nl":"Nederlandese",
 "nn":"Norvegese nynorsk",
 "nr":"Ndebele meridionale",
 "nso":"Sesotho del nord",
 "nv":"Navajo",
 "ny":"Chichewa",
 "oc":"Occitano",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Osseto",
 "pa":"Panjabi",
 "pi":"Pali",
 "pl":"Polacco",
 "ps":"Paštu",
 "pt":"Portoghese",
 "pt_BR":"Portoghese brasiliano",
 "qu":"Quechua",
 "rn":"Kirundi",
 "ro":"Rumeno",
 "rom":"Romaní",
 "ru":"Russo",
 "rw":"Kinyarwanda",
 "sa":"Sanscrito",
 "sc":"Sardo",
 "sd":"Sindhi",
 "se":"Sami settentrionale",
 "sg":"Sango",
 "si":"Singalese",
 "sk":"Slovacco",
 "sl":"Sloveno",
 "sm":"Samoano",
 "sn":"Shona",
 "so":"Somalo",
 "sq":"Albanese",
 "sr":"Serbo",
 "sr@ijekavian":"Serbo ijekavo",
 "sr@ijekavianlatin":"Serbo ijekavo latino",
 "sr@latin":"Serbo latino",
 "ss":"Swati",
 "st":"Sesotho meridionale",
 "su":"Sondanese",
 "sv":"Svedese",
 "sw":"Swahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Tagico",
 "th":"Thailandese",
 "ti":"Tigrino",
 "tk":"Turkmeno",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turco",
 "ts":"Tsonga",
 "tt":"Tataro",
 "tw":"Twi",
 "ty":"Tahitiano",
 "ug":"Uiguro",
 "uk":"Ucraino",
 "ur":"Urdu",
 "uz":"Usbeco",
 "uz@cyrillic":"Usbeco (cirillico)",
 "ven":"Venda",
 "vi":"Vietnamita",
 "vo":"Volapük",
 "wa":"Vallone",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Yiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Cinese",
 "zh_CN":"Cinese semplificato",
 "zh_HK":"Cinese (Hong Kong)",
 "zh_TW":"Cinese tradizionale",
 "zu":"Zulu",
},
"nl": {
 "aa":"Afar",
 "ab":"Abkhazian",
 "ae":"Avestan",
 "af":"Afrikaans",
 "am":"Amharisch",
 "ar":"Arabisch",
 "as":"Assamees",
 "ast":"Asturisch",
 "ay":"Aymara",
 "az":"Azerbeidjaans",
 "ba":"Bashkir",
 "be":"Wit-Rusland",
 "be@latin":"Wit-Rusland (Latijn)",
 "bg":"Bulgaars",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengali",
 "bn_IN":"Bengali (India)",
 "bo":"Tibetaans",
 "br":"Bretons",
 "bs":"Bosnisch",
 "ca":"Catalaans",
 "ca@valencia":"Catalaans (Valentiaans)",
 "ce":"Chechen",
 "ch":"Chamorro",
 "co":"Corsicaans",
 "crh":"Krimtartaar",
 "cs":"Tsjechisch",
 "csb":"Kashubian",
 "cu":"Kerk Slavisch",
 "cv":"Chuvash",
 "cy":"Welsh",
 "da":"Deens",
 "de":"Duits",
 "dsb":"Nedersorbisch",
 "dz":"Dzongkha",
 "el":"Grieks",
 "en":"Engels",
 "en_GB":"Engels (Brits)",
 "en_US":"Engels (Amerikaans)",
 "eo":"Esperanto",
 "es":"Spaans",
 "et":"Ests",
 "eu":"Baskisch",
 "fa":"Farsi (Perzisch)",
 "fi":"Fins",
 "fj":"Fijisch",
 "fo":"Faroese",
 "fr":"Frans",
 "fy":"Frysk",
 "ga":"Gaelic (Iers)",
 "gd":"Gaelic",
 "gl":"Galicisch",
 "gn":"Guarani",
 "gu":"Gujarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"Hebreeuws",
 "hi":"Hindi",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Kroatisch",
 "hsb":"Opper Sorbian",
 "hu":"Hongaars",
 "hy":"Armeens",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"Indonesisch",
 "ie":"Interlingue",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"IJslands",
 "it":"Italiaans",
 "iu":"Inuktitut",
 "ja":"Japans",
 "jv":"Javaans",
 "ka":"Georgisch",
 "ki":"Kikuyu",
 "kk":"Kazakh",
 "kl":"Kalaallisut",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Koreaans",
 "ks":"Kashmiri",
 "ku":"Koerdisch",
 "kv":"Komi",
 "kw":"Cornish",
 "ky":"Kirghizisch",
 "la":"Latijn",
 "lb":"Letzenburgs",
 "li":"Limburgs",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Litouws",
 "lv":"Lets",
 "mai":"Maithili",
 "mg":"Malagasy",
 "mh":"Marshallees",
 "mi":"Maori",
 "mk":"Macedonisch",
 "ml":"Malayalam",
 "mn":"Mongolisch",
 "mo":"Moldavisch",
 "mr":"Marathi",
 "ms":"Malay",
 "mt":"Maltees",
 "my":"Burmees",
 "na":"Nauru",
 "nb":"Noors Bokmål",
 "nd":"Ndebele, Noord",
 "nds":"Nedersaksisch",
 "ne":"Nepalees",
 "ng":"Ndonga",
 "nl":"Nederlands",
 "nn":"Noors, Nynorsk",
 "nr":"Ndebele, Zuid",
 "nso":"Noord-Sotho",
 "nv":"Navajo",
 "ny":"Chichewa",
 "oc":"Occitan",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Ossetisch",
 "pa":"Panjabi",
 "pi":"Pali",
 "pl":"Pools",
 "ps":"Pushto",
 "pt":"Portugees",
 "pt_BR":"Braziliaans Portugees",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Roemeens",
 "rom":"Roma",
 "ru":"Russisch",
 "rw":"Kinyarwanda",
 "sa":"Sanskrit",
 "sc":"Sardinisch",
 "sd":"Sindhi",
 "se":"Noord Sami",
 "sg":"Sango",
 "si":"Singalees",
 "sk":"Slowaaks",
 "sl":"Sloweens",
 "sm":"Samoaans",
 "sn":"Shona",
 "so":"Somalisch",
 "sq":"Albanisch",
 "sr":"Servisch",
 "sr@ijekavian":"Servisch Ijekavian",
 "sr@ijekavianlatin":"Servisch Ijekavian Latijn",
 "sr@latin":"Servisch Latijn",
 "ss":"Swati",
 "st":"Sotho, Zuid",
 "su":"Sundanees",
 "sv":"Zweeds",
 "sw":"Swahili",
 "ta":"Tamil",
 "te":"Telugu",
 "tg":"Tajiks",
 "th":"Thais",
 "ti":"Tigrinya",
 "tk":"Turkmeens",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Turks",
 "ts":"Tsonga",
 "tt":"Tatar",
 "tw":"Twi",
 "ty":"Tahitiaans",
 "ug":"Uighur",
 "uk":"Oekraïns",
 "ur":"Urdu",
 "uz":"Oezbeeks",
 "uz@cyrillic":"Oezbeeks (Cyrilisch)",
 "ven":"Venda",
 "vi":"Vietnamees",
 "vo":"Volapúk",
 "wa":"Waals",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Yiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Chinees",
 "zh_CN":"Chinees (Vereenvoudigd)",
 "zh_HK":"Chinees (Hong Kong)",
 "zh_TW":"Chinees (Traditioneel)",
 "zu":"Zulu",
},
"ru": {
 "aa":"Афарский",
 "ab":"Абхазский",
 "ae":"Авестийский",
 "af":"Африкаанс",
 "am":"Амхарский",
 "ar":"Арабский",
 "as":"Ассамский",
 "ast":"Астурийский",
 "ay":"Аймарский",
 "az":"Азербайджанский",
 "ba":"Башкирский",
 "be":"Белорусский",
 "be@latin":"Белорусский (латиница)",
 "bg":"Болгарский",
 "bh":"Бихарский",
 "bi":"Бислама",
 "bn":"Бенгальский",
 "bn_IN":"Бенгальский (Индия)",
 "bo":"Тибетский",
 "br":"Бретонский",
 "bs":"Боснийский",
 "ca":"Каталонский",
 "ca@valencia":"Каталонский (Валенсия)",
 "ce":"Чеченский",
 "ch":"Чаморро",
 "co":"Корсиканский",
 "crh":"Крымско-татарский",
 "cs":"Чешский",
 "csb":"Кашубский",
 "cu":"Церковнославянский",
 "cv":"Чувашский",
 "cy":"Уэльский",
 "da":"Датский",
 "de":"Немецкий",
 "dsb":"Нижнелужицкий",
 "dz":"Дзонгка (Бутан)",
 "el":"Греческий",
 "en":"Английский",
 "en_GB":"Английский (Великобритания)",
 "en_US":"Английский (США)",
 "eo":"Эсперанто",
 "es":"Испанский",
 "et":"Эстонский",
 "eu":"Баскский",
 "fa":"Персидский",
 "fi":"Финский",
 "fj":"Фиджи",
 "fo":"Фарерский",
 "fr":"Французский",
 "fy":"Фризский",
 "ga":"Ирландский",
 "gd":"Шотландский",
 "gl":"Галисийский",
 "gn":"Гуарани",
 "gu":"Гуджарати",
 "gv":"Мэнский",
 "ha":"Хауса",
 "he":"Иврит",
 "hi":"Хинди",
 "hne":"Чхаттисгархи",
 "ho":"Хири-моту",
 "hr":"Хорватский",
 "hsb":"Верхнелужицкий",
 "hu":"Венгерский",
 "hy":"Армянский",
 "hz":"Эреро",
 "ia":"Интерлингва",
 "id":"Индонезийский",
 "ie":"Окциденталь",
 "ik":"Инупиак",
 "io":"Идо",
 "is":"Исландский",
 "it":"Итальянский",
 "iu":"Инуктитут",
 "ja":"Японский",
 "jv":"Яванский",
 "ka":"Грузинский",
 "ki":"Кикуйю",
 "kk":"Казахский",
 "kl":"Гренландский",
 "km":"Кхмерский",
 "kn":"Каннада",
 "ko":"Корейский",
 "ks":"Кашмирский",
 "ku":"Курдский",
 "kv":"Коми",
 "kw":"Корнский",
 "ky":"Киргизский",
 "la":"Латинский",
 "lb":"Люксембургский",
 "li":"Лимбуржский",
 "ln":"Лингала",
 "lo":"Лаосский",
 "lt":"Литовский",
 "lv":"Латышский",
 "mai":"Майтхили",
 "mg":"Мальгашский",
 "mh":"Маршалльский",
 "mi":"Маори",
 "mk":"Македонский",
 "ml":"Малаялам",
 "mn":"Монгольский",
 "mo":"Молдавский",
 "mr":"Маратхи",
 "ms":"Малайский",
 "mt":"Мальтийский",
 "my":"Бирманский",
 "na":"Науру",
 "nb":"Норвежский (литературный)",
 "nd":"Северный ндебеле",
 "nds":"Нижнесаксонский",
 "ne":"Непальский",
 "ng":"Ндонга",
 "nl":"Голландский",
 "nn":"Норвежский (нюнорск)",
 "nr":"Южный ндебеле",
 "nso":"Северный сото",
 "nv":"Навахо",
 "ny":"Чичева",
 "oc":"Окситанский",
 "om":"Оромо",
 "or":"Ория",
 "os":"Осетинский",
 "pa":"Панджаби",
 "pi":"Пали",
 "pl":"Польский",
 "ps":"Пушту",
 "pt":"Португальский",
 "pt_BR":"Португальский (Бразилия)",
 "qu":"Кечуа",
 "rn":"Рунди",
 "ro":"Румынский",
 "rom":"Цыганский",
 "ru":"Русский",
 "rw":"Киньяруанда",
 "sa":"Санскрит",
 "sc":"Сардинский",
 "sd":"Синдхи",
 "se":"Северносаамский",
 "sg":"Санго",
 "si":"Сингальский",
 "sk":"Словацкий",
 "sl":"Словенский",
 "sm":"Самоанский",
 "sn":"Шона",
 "so":"Сомалийский",
 "sq":"Албанский",
 "sr":"Сербский",
 "sr@ijekavian":"Сербский (иекавский)",
 "sr@ijekavianlatin":"Сербский (иекавский, латиница)",
 "sr@latin":"Сербский (латиница)",
 "ss":"Свати",
 "st":"Южный сото",
 "su":"Сунданский",
 "sv":"Шведский",
 "sw":"Суахили",
 "ta":"Тамильский",
 "te":"Телугу",
 "tg":"Таджикский",
 "th":"Тайский",
 "ti":"Тигринья",
 "tk":"Туркменский",
 "tn":"Тсвана",
 "to":"Тонганский",
 "tr":"Турецкий",
 "ts":"Тсонга",
 "tt":"Татарский",
 "tw":"Тви",
 "ty":"Таитянский",
 "ug":"Уйгурский",
 "uk":"Украинский",
 "ur":"Урду",
 "uz":"Узбекский",
 "uz@cyrillic":"Узбекский (кириллица)",
 "ven":"Венда",
 "vi":"Вьетнамский",
 "vo":"Волапюк",
 "wa":"Валлонский",
 "wo":"Волоф",
 "xh":"Коса",
 "yi":"Идиш",
 "yo":"Йоруба",
 "za":"Чжуанский",
 "zh":"Китайский",
 "zh_CN":"Китайский (Китай)",
 "zh_HK":"Китайский (Гонконг)",
 "zh_TW":"Китайский (Тайвань)",
 "zu":"Зулусский",
},
"tr": {
 "aa":"Afar",
 "ab":"Abkhazian",
 "ae":"Avestan",
 "af":"Afrika Dili",
 "am":"Amharic",
 "ar":"Arapça",
 "as":"Assamese",
 "ast":"Avusturya Dili",
 "ay":"Aymara",
 "az":"Azerbeycanca",
 "ba":"Bashkir",
 "be":"Belarus Dili",
 "be@latin":"Belarus Dili (Latin)",
 "bg":"Bulgarca",
 "bh":"Bihari",
 "bi":"Bislama",
 "bn":"Bengalce",
 "bn_IN":"Bengalce (Hindistan)",
 "bo":"Tibetan",
 "br":"Britanya Dili",
 "bs":"Boşnakça",
 "ca":"Katalan Dili",
 "ca@valencia":"Katalan (Valencia)",
 "ce":"Çeçen",
 "ch":"Chamorro",
 "co":"Korsikaca",
 "crh":"Kırım Tatarcası",
 "cs":"Çekçe",
 "csb":"Kashubian",
 "cu":"Church Slavic",
 "cv":"Çuvaşça",
 "cy":"Gallerce",
 "da":"Danimarka Dili",
 "de":"Almanca",
 "dsb":"Aşağı Sırpça",
 "dz":"Dzongkha",
 "el":"Yunanca",
 "en":"İngilizce",
 "en_GB":"İngiliz İngilizcesi",
 "en_US":"Amerikan İngilizcesi",
 "eo":"Esperanto",
 "es":"İspanyolca",
 "et":"Estonya Dili",
 "eu":"Bask Dili",
 "fa":"Farsça (İran)",
 "fi":"Fince",
 "fj":"Fijian",
 "fo":"Faroese",
 "fr":"Fransızca",
 "fy":"Frisian",
 "ga":"İrlanda Galik",
 "gd":"Galik",
 "gl":"Galce",
 "gn":"Guarani",
 "gu":"Gujarati",
 "gv":"Manx",
 "ha":"Hausa",
 "he":"İbranice",
 "hi":"Hintçe",
 "hne":"Chhattisgarhi",
 "ho":"Hiri Motu",
 "hr":"Hırvatça",
 "hsb":"Yukarı Sırpça",
 "hu":"Macarca",
 "hy":"Ermenice",
 "hz":"Herero",
 "ia":"Interlingua",
 "id":"İndonezya Dili",
 "ie":"Interlingue",
 "ik":"Inupiaq",
 "io":"Ido",
 "is":"İzlanda Dili",
 "it":"İtalyanca",
 "iu":"Inuktitut",
 "ja":"Japonca",
 "jv":"Javanese",
 "ka":"Gürcüce",
 "ki":"Kikuyu",
 "kk":"Kazakça",
 "kl":"Kalaallisut",
 "km":"Khmer",
 "kn":"Kannada",
 "ko":"Korece",
 "ks":"Kashmiri",
 "ku":"Kürtçe",
 "kv":"Komi",
 "kw":"Cornish",
 "ky":"Kırgız",
 "la":"Latin",
 "lb":"Luxembourgish",
 "li":"Limburgan",
 "ln":"Lingala",
 "lo":"Lao",
 "lt":"Litvanya Dili",
 "lv":"Litvanya Dili",
 "mai":"Maithili",
 "mg":"Malagasy",
 "mh":"Marshallese",
 "mi":"Maori Dili",
 "mk":"Makedonca",
 "ml":"Malayalam",
 "mn":"Moğolca",
 "mo":"Moldavya Dili",
 "mr":"Marathi",
 "ms":"Malay",
 "mt":"Malta Dili",
 "my":"Burmese",
 "na":"Nauru",
 "nb":"Norveççe Bokmål",
 "nd":"Ndebele, North",
 "nds":"Aşağı Saksonca",
 "ne":"Nepalce",
 "ng":"Ndonga",
 "nl":"Flamanca",
 "nn":"Norveççe Nynorsk",
 "nr":"Ndebele, South",
 "nso":"Northern Sotho",
 "nv":"Navajo",
 "ny":"Chichewa",
 "oc":"Oksitan dili",
 "om":"Oromo",
 "or":"Oriya",
 "os":"Ossetian",
 "pa":"Punjabi/Panjabi",
 "pi":"Pali",
 "pl":"Lehçe",
 "ps":"Pushto",
 "pt":"Portekizce",
 "pt_BR":"Brezilya Portekizcesi",
 "qu":"Quechua",
 "rn":"Rundi",
 "ro":"Romence",
 "rom":"Çingene Dili",
 "ru":"Rusça",
 "rw":"Kinyarwanda",
 "sa":"Sanskrit",
 "sc":"Sardinian",
 "sd":"Sindhi",
 "se":"Northern Sami",
 "sg":"Sango",
 "si":"Sinhala",
 "sk":"Slovakça",
 "sl":"Slovence",
 "sm":"Samoan",
 "sn":"Shona",
 "so":"Somalice",
 "sq":"Albanian",
 "sr":"Sırpça",
 "sr@ijekavian":"Sırpça Ijekavian",
 "sr@ijekavianlatin":"Sırpça Ijekavian Latin",
 "sr@latin":"Sırpça Latin",
 "ss":"Swati",
 "st":"Sotho, Southern",
 "su":"Sundanese",
 "sv":"İsveççe",
 "sw":"Swahili",
 "ta":"Tamil Dili",
 "te":"Telugu",
 "tg":"Tajik",
 "th":"Thai",
 "ti":"Tigrinya",
 "tk":"Türkmence",
 "tn":"Tswana",
 "to":"Tonga",
 "tr":"Türkçe",
 "ts":"Tsonga",
 "tt":"Tatar",
 "tw":"Twi",
 "ty":"Tahitian",
 "ug":"Uygurca",
 "uk":"Ukrayna Dili",
 "ur":"Urdu",
 "uz":"Özbek",
 "uz@cyrillic":"Özbekçe (Kiril)",
 "ven":"Venda",
 "vi":"Vietnamca",
 "vo":"Volapük",
 "wa":"Valonca",
 "wo":"Wolof",
 "xh":"Xhosa",
 "yi":"Yiddish",
 "yo":"Yoruba",
 "za":"Zhuang",
 "zh":"Çince",
 "zh_CN":"Basitleştirilmiş Çince",
 "zh_HK":"Çince (Hong Kong)",
 "zh_TW":"Geleneksel Çince",
 "zu":"Zulu",
},
}

# End of data.py
