name: Build Frescobaldi installers

on: push

jobs:
  build:
    name: Build Windows installer
    if: startsWith(github.ref, 'refs/tags/')  # run only on tag pushes (releases)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install NSIS
      run: |
        choco install nsis
    - name: Install pynsist
      run: |
        python -m pip install --upgrade pip
        pip install pynsist
    - name: Build the .exe file
      run: |
        pynsist windows-installer.cfg
    - uses: actions/upload-artifact@v4
      with:
        path: build/nsis/
        name: windows-installer
